import = [
  "~/.config/alacritty/kanagawa-alacritty.toml"
  # "~/.config/alacritty/kanagawa-dragon-alacritty.toml"
  # "~/.config/alacritty/nordic-alacritty.toml"
]

[font]
size = 17.0

[font.normal]
family = "Iosevka"
style = "Light"

[font.bold]
style = "Semibold"

[font.bold_italic]
style = "Semibold Oblique"

[font.italic]
style = "Light Oblique"

[window]
decorations = "none"
